### PR TITLE
Add project pages and dependency resolution

### LINKED ISSUE #33: Provide a browsable version of project pages
We should provide an HTML page for every package, intended for users to browse packages on the piwheels website, akin to the browsable package index on PyPI: e.g. https://pypi.python.org/pypi/numpy

We would provide package pages at `/piwheels/<package>` (unless anyone has a better suggestion).

I imagine the process to generate pages would be alongside where we currently generate the links page in `/simple/<package>`.

Based on a template (using the homepage style), this could include a list of versions, and maybe something like checkboxes for which builds we have (python version / etc). Bit tricky due to some being "none", others being py3, others being cp34m.

I have started work on the template and I will try to get a basic version working...

### LINKED ISSUE #59: Store user dependencies in database
When installing something like opencv from piwheels, it doesn't work until the user dependencies are satisfied - not pip dependencies as these are obviously covered by pip itself, but apt dependencies.

It would be good if we were able to log these in the database (could just be a text field with html - or even just assume it's all commands and stick the whole thing in a `<pre>`) and render them on the project pages (coming in #33). We'd only do it for a select few, and allow additions via github issue, no need to do more than that.

- [x] Database change
- [x] Algorithm to calculate dependencies
- [x] Enhance importer to permit manual dependency specification
- [x] Inclusion in web pages

### PR DESCRIPTION
**Pull request by waveform80**
A substantial PR (sorry!) which finally adds dependency calculation to the build slaves, dependency storage on the server side, and dependency display in the new project pages. Also tidies up some of the bits surrounding project pages, and the scribe task getting overloaded with generating them.

The project pages themselves probably need a bit more work (aesthetically speaking) but the content should all be complete once this PR lands.

@bennuttall it's probably pointless trying to review this (it's huge) but if you've got a few Pis spare to give it a proper run (I've given it a run on a single Pi here) that'd be great.

Deployment of this is going to be relatively painful. First all the build slaves and the master need updating, second the database needs updating, and third we need to take a snapshot of all the files we need to regenerate dependencies for before restarting the master then write a custom script to delete those builds, prompting their re-run.

fixes #33 and #59

### CODE REVIEW

**Comment by bennuttall** [comment]
Wow - great! I've skimmed through the changes and it looks good. I'll spin up a few Pis to test it as soon as I get chance :+1: 

Did you say we need to rebuild everything not pure python to calculate dependencies? Or can we get the builders to calculate them from the existing wheels (on the same builder)?

**Comment by waveform80** [comment]
Yup, we need to rebuild all the non-pure Python stuff. Theoretically we could get the builders to calculate them, but that means writing a load of custom stuff to download wheels to appropriate builders, calculate the deps, and use some custom protocol to patch the dependencies into the database. Frankly it's just easier to rebuild them given it's a (small) minority of wheels.

**Comment by waveform80** [comment]
That said, I need to build a couple of custom scripts to regenerate the version release dates and skip reasons but that's actually pretty trivial and I can do it offline and patch the database later.

**Comment by bennuttall** [comment]
Will deleting builds remove download stats?

**Pull request merged**
